### ISSUE TITLE
not an issue - question on line detection research

### ISSUE THREAD

**Issue by johndpope** [aleksispi/drl-rpn-tf#1]
are you aware of any work to do simple line detection using ML?
the hough transform is terribly expensive and i'd like to fine a cheap way to do in real time for mobile. https://en.wikipedia.org/wiki/Hough_transform
This is usually done with canny line detection. but I have a suspicious losing the colors is throwing away potentially useful information. 

There's is  Parallel Coordinate lines — Line detection 
http://medusa.fit.vutbr.cz/public/data/papers/2011-CVPR-Dubska-PClines.pdf

https://github.com/syagev/deep-ellipse/issues/1

 if the nets could be trained to find the lines / then this could be put into a pipeline of further computations to find perspectives / walls etc.

**Comment by aleksispi** [comment]
Hi! Sorry, but I don't have any such experience. There are fast detectors such as yolo v3 you could check out.
