### ISSUE TITLE
Is there a code of visualization available？

### ISSUE THREAD

**Issue by MightyAtom520** [aleksispi/drl-rpn-tf#11]
Hello，I need to visualize the conseqences of ROI, to present the process of choosing the bounding boxes.  Could you please offer me the code of visualization? Thanks a lot.

**Comment by aleksispi** [comment]
Hi! Sorry, don't have that code available and I'm not able to create such code. But as I remember it, it wasn't super hard to add the necessary lines of matplotlib in the main agent interaction loop and track whatever fixations it makes and plot them.

Best of luck!

**Comment by MightyAtom520** [comment]
Copy that. Thanks.



---- Replied Message ----
| From | Aleksis ***@***.***> |
| Date | 04/11/2023 15:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [aleksispi/drl-rpn-tf] Is there a code of visualization available？ (Issue #11) |

Hi! Sorry, don't have that code available and I'm not able to create such code. But as I remember it, it wasn't super hard to add the necessary lines of matplotlib in the main agent interaction loop and track whatever fixations it makes and plot them.

Best of luck!
