### ISSUE TITLE
Joint Training of Policy and Detector problem

### ISSUE THREAD

**Issue by chang010453** [aleksispi/drl-rpn-tf#5]
In your paper's section 5.3, it says **theta_base and theta_det** would be trained.
In your code, they training at **train_det** mode.
But I look into the gradients it produce, **only theta_det can be update, there is no gradient in theta_base.**
Can you check this problem?
thanks.

**Comment by aleksispi** [comment]
Hi,

The code does not support training of theta_base. See page 5 in the paper http://openaccess.thecvf.com/content_cvpr_2018/papers/Pirinen_Deep_Reinforcement_Learning_CVPR_2018_paper.pdf, where in the footnote 5 we write that theta_base is frozen as we saw no improvement by training those parameters.

If you would like to investigate also training the full system, probably a good place to start is the Faster R-CNN code that I built drl-RPN on top of. That code base should support training theta_base too: https://github.com/endernewton/tf-faster-rcnn. Hopefully you should be able to mimic the code they use for training theta_base and insert to the drl-RPN code.

Cheers,
Aleksis
