### ISSUE TITLE
Can i use the Demo.py which in tf-faster-rcnn?

### ISSUE THREAD

**Issue by zhijiejia** [aleksispi/drl-rpn-tf#6]
Hey!
Can i use the Demo.py which in tf-faster-rcnn? I want to see the visable outputs.

But when i run the demo.py, it present the follow error.

`
create_architecture() got multiple values for argument 'tag' 
`

Can you give some advise? Thanks.

**Comment by aleksispi** [comment]
Hi zhijiejia ,

I don't think this repo supports using that demo file, it may be a relic from the tf-faster-rcnn repository. You may be able to transfer some visualization code from the demo somewhere to make a custom code for visualization. I don't have such code available, sorry.

Cheers,
Aleksis
