### ISSUE TITLE
How can i train my custom data without pretrained weight?

### ISSUE THREAD

**Issue by leesing9** [aleksispi/drl-rpn-tf#8]
I'm trying to train drlrpn using a custom dataset with a different number of classes.
However, if "WEIGHTS_PATH" is not entered, an error occurs.
How can i train my custom data without pretrained weight?

**Comment by aleksispi** [comment]
Hi leesing9,

The code only supports using some set of pretrained weights. In this case, a pretrained Faster R-CNN model, which is the the starting point for the drl-RPN, is used. If you would randomly initialize those weights instead (which I don't think the code currently supports, but you could implement yourself), make sure you add code that can refine also the backbone network. The current code only supports refinement of the later layers of the network, as it was empirically noted that refining also the base network did not affect detection accuracy.

Cheers,
Aleksis
